### ISSUE TITLE
RectMode Center

### ISSUE THREAD

**Issue by aidano-7** [bmoren/p5.collide2D#27]
the rect mode center mode is not supported in the library

**Comment by bmoren** [comment]
Yes, correct it is not supported as of right now. 

It would require a duplicate set of functions or offsets for every function so I have not been able to implement it as of yet due to need vs time constraints. If its something you're interested in working on, I'd love to add support for this to the library (as well as` ellipseMode(CORNER)`) in the future!

**Comment by wisehackermonkey** [comment]
this could be added with `collisionMode(CENTER)` #28

**Comment by dipamsen** [comment]
### My small contribution: 

This is the basic implementation of `rectMode(CENTER)` in my mind: 

The following image shows the difference between `rectMode(CENTER)` and `rectMode(CORNER)` 
![image](https://user-images.githubusercontent.com/59444569/89803496-87c62d80-db50-11ea-9be4-2cdaf375fbca.png)
- We are having the implementation of  `rectMode(CORNER)` (Figure 1)
- When `rectMode` is `CENTER`, we need to find x and y positions **in the corner** to match those in **Figure 1** so as to use the logic of   `rectMode(CORNER)`.

### This will be the logic (pseudocode) for `collideRectRect()` function.
```javascript
// this code will be in the collideRectRect() function before the collision checking

if (rectMode is CENTER) { // If current RectMode is CENTER

  // We have to change our points so that it matches with rectMode(CORNER) logic

  // Width and Height stays same in both Modes.
  // So we need to change x, y, x2 and y2.

  x = x - w / 2;  
  y = y - h / 2;
  x2 = x2 - w2 / 2;
  y2 = y2 - h2 / 2;
}
```
### Live Demo
https://editor.p5js.org/dipam2006/sketches/9yJ6FzABZ
(Change the `_rectMode` variable on line 11 to see interactions. Modified function code: Line 40.)

**Comment by dipamsen** [comment]
@bmoren 

#### I worked on [all the possible `rectMode()`s](https://p5js.org/reference/#/p5/rectMode), and came up with this:

### Live Demo: `collideRectRect()` function with variable `rectMode()`
https://editor.p5js.org/dipam2006/sketches/4PLk9FrQ3

(change line 9 to see different modes, change rectangle dimensions in line 12-23)

- `rectMode(CORNER)` (default)
- `rectMode(CORNERS)` 
- `rectMode(CENTER)` 
- `rectMode(RADIUS)`

### How this works
Converts function parameters such that it matches logic of `rectMode(CORNER)` (default).
```javascript
  if (_rectMode == CORNER) {
    // everything remains same
    [_x, _y, _w, _h, _x2, _y2, _w2, _h2] = [x, y, w, h, x2, y2, w2, h2]
  }
  if (_rectMode == CENTER) {
    _x = x - w / 2;
    _y = y - h / 2;
    _x2 = x2 - w2 / 2;
    _y2 = y2 - h2 / 2;
    // width and height remain same
    [_w, _h, _w2, _h2] = [w, h, w2, h2];
  }
  if (_rectMode == CORNERS) {
    // Finding Width and height
    _w = w > x ? w - x : x - w;
    _h = h > y ? h - y : y - h;
    _w2 = w2 > x2 ? w2 - x2 : x2 - w2;
    _h2 = h2 > y2 ? h2 - y2 : y2 - h2;

    // x, y and x2, y2 should be at top left
    // x of left side will be either x or w
    _x = min(x, w);
    _y = min(y, h);
    _x2 = min(x2, w2);
    _y2 = min(y2, h2);
  }
  if (_rectMode == RADIUS) {
    // width and height doubles
    [_w, _h, _w2, _h2] = [w, h, w2, h2].map(a => a * 2);
    // We need to calculate with new width and height
    // (same as rectMode(CENTER))
    _x = x - _w / 2;
    _y = y - _h / 2;
    _x2 = x2 - _w2 / 2;
    _y2 = y2 - _h2 / 2;
  }
/**
collision checking
*/
```
### Improvement
- This is a large amount of code for a single function, I think this same code can be reduced.
- Implementation: `collisionMode()`?
- All the collide functions with rect will have this to convert it to `rectMode(CORNER)`
- If anyone has a better idea with shorter code, I would love to know that!

Nextly I would try to do this for `ellipseMode()` (they are the same as `rectMode()`)

**Comment by bmoren** [comment]
Hi @dipamsen, some great work here thank you!

A few thoughts –

There will be no collisionMode() as of now. We decided to implement the independent function for vector versions instead for clarity.

This does seem like a lot of code. I feel like your approach is generally going in the direction I would go starting this as well. I think the task becomes instead of having to re-do this for every function, is there a nice way to package up that work to make it reusable so at the very least it can be dropped into each function as a single call. here's some very psuedocode for an idea? maybe?

```javascript

function convertRectMode(_x, _y, _w, _h, _x2, _y2, _w2, _h2){

  if (_rectMode == CORNER) {
    // everything remains same
    return {x:_x, y: _y, w:_w, h:_h, w2:_x2,y2: _y2, w2:_w2, h2:_h2
  }

  if (_rectMode == CENTER) {
   return { _x = x - w / 2,
    y : y - h / 2,
    x2 : x2 - w2 / 2,
    y2 : y2 - h2 / 2,
    w : _w,
    h : _h,  
    w2 : _w2, 
    h2 : _h2
}
//etc.etc.etc.


}


//usage:

p5.prototype.collideRectRect = function (x, y, w, h, x2, y2, w2, h2) {

let c = convertRectMode(x, y, w, h, x2, y2, w2, h2)

  //2d
  //add in a thing to detect rectMode CENTER
  if (c.x + c.w >= c.x2 &&    // r1 right edge past r2 left
      c.x <= c.x2 + c.w2 &&    // r1 left edge past r2 right
      c.y + c.h >= c.y2 &&    // r1 top edge past r2 bottom
      c.y <= c.y2 + c.h2) {    // r1 bottom edge past r2 top
        return true;
  }
  return false;
};


```

potential issues:
+ would need to rewrite all of the functions to take in the output of the conversion to JSON objects
+ might negatively effect performance dramatically

positives:
+ would allow one function to be used over and over for every function

followups:
+ how does p5 actually handle this change behind the scenes?
+ https://github.com/processing/p5.js/blob/main/src/core/shape/attributes.js#L115

**Comment by bmoren** [comment]
as suspected, my idea above is substantially slower: https://jsbench.me/7oke07hze2/1

**Comment by bmoren** [comment]
I'm now thinking that this is maybe not worth supporting given what it would take to do it performantly. But perhaps, better to implement as an example where we'd show switching modes on the fly to achieve the same basic Idea: https://editor.p5js.org/benmoren/sketches/UfumfyHTd

**Comment by dipamsen** [comment]
I know that this issue is not being worked on anymore, but just in case:
The current `rectMode` is stored in `_renderer._rectMode`
