### ISSUE TITLE
[Fix/housekeeping] CDN Update issue, [AUTO] Bump Version Tag?

### ISSUE THREAD

**Issue by wisehackermonkey** [bmoren/p5.collide2D#33]
# Issue:
#### Hi @bmoren!  i was testing out code with the latest vector pull request merged #28 , looks like CDN's doesn't register the change because the version number hasnt been updated. 

# Solution:
#### Add a updated tag to reflect the change
```
v0.6 -> v0.7 
```

[Link to Example of cdn not updating issue](https://editor.p5js.org/wisemonkey/sketches/U-dE0Ns6P)
# Photos of issue
[![image.png](https://i.postimg.cc/5yn6zQBM/image.png)](https://postimg.cc/dZZsP1NW)
![](https://i.postimg.cc/tTn52yrf/image.png)
[![image.png](https://i.postimg.cc/Bvk58kqC/image.png)](https://postimg.cc/Y4NLZXL4)
[![image.png](https://i.postimg.cc/kghKZztd/image.png)](https://postimg.cc/bZkZS6T6)

**Comment by bmoren** [comment]
I have issued a new release on github which I think should sort this out, if you can wait a bit and then check again / confirm that would be awesome. Also, I was thinking since we've got the auto-build for the min setup now with your contribution, perhaps it makes sense to auto release a version when it sees a version bump? or maybe this is best handled manually as to not flood the versions? any thoughts on that?

**Comment by bmoren** [comment]
fixed!

https://cdn.jsdelivr.net/gh/bmoren/p5.collide2D@0.7/p5.collide2d.min.js

**Comment by wisehackermonkey** [comment]
# Auto bumping  the version numbers on git tag creation 
### sounds like a good idea.

# workflow diagram
### heres what i was thinking 
![](https://yuml.me/9962b9b0.png)
![](http://yuml.me/1c9ff09c.png)
## I think there is a github action for that specific task, so it might be a easy change

**Comment by bmoren** [comment]
yes, I'm open to this for sure. I've never tagged from the command line so I'm partial to the `release created > gh action` idea. I think this could also be combined with the current minify action so that it's not happening every commit, but instead when a version is explicitly ready for a release. This would avoid polluting the minified version while updates are being made to the verbose version.

So the gh action on release created would ideally:
+ bump version #s (based on the release tag?)
+ minify
+ publish version update to NPM (does this happen automatically?)

I'm re-opening this issue to address this new idea/issue

**Comment by wisehackermonkey** [comment]
# Thought
###  actually i think every commit should get its own patch version
### and major and minor version bumps should be manual

# reasoning: 
### Auto bump every commit
#### Pro:
- major versions should break compatibility [Manual]
- minor version dont break compatibility but add features [Manual]
- patches fix bugs [Automatic]
Con:
- patch bug fixes wont go be delivered through cdn's

### Manual version bump on group of stable commits:
#### Pro:
- cdn's will get bug fixes and small updates and the user doesn't have to change the code
- cleaner version numbers
#### Con:
- a change to the code could break compatibility with people's existing projects
- more hands on, mantainnes

Clarification: 
`gh action is the build script`

## what I was thinking what would happen:

- create release tag for major and minor version bumps [manual]
> via [here](https://github.com/bmoren/p5.collide2D/tag) or in the command line using `git tag X.X.X`
- github action build script is triggered [automatically]
 - bump version #s based on the release tag [automatically]
 - minify [automatically]
 - publish version update to NPM [automatically]

### Question: `publish version update to NPM (does this happen automatically?)` 
#### Answer: its automatic based on the latest git tag

**Comment by wisehackermonkey** [comment]
Ill make a pull request with a the code that auto bumps the version number on creation of release tag

**Comment by wisehackermonkey** [comment]
Done code should be here #38
